const state={city:'Hyderabad',mode:'local',intent:null,filters:{budget:null,time:null,nearby:false}};
const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);let toastTimer;
function toast(msg){let el=$('#toast');if(!el){el=document.createElement('div');el.id='toast';el.className='toast';document.body.appendChild(el)}el.textContent=msg;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2200)}
function currency(){return state.city==='Hyderabad'?'INR':'AED'}
function budgetLimit(){return currency()==='INR'?500:50}
function updateContext(){const mode=state.mode==='local'?'For locals':state.mode==='visitor'?'For visitors':'For curious explorers';$('#contextLabel').textContent=`${mode} in ${state.city}`}
function setMode(mode){state.mode=mode;$$('.mode').forEach(b=>{const active=b.dataset.mode===mode;b.classList.toggle('active',active);b.setAttribute('aria-selected',String(active))});updateContext();renderRecommendations();toast(mode==='local'?'Local mode selected':mode==='visitor'?'Visitor mode selected':'Explore mode selected')}
function score(place){let s=0;const cat=place.categories||[];const best=place.bestFor||[];const cls=place.classification||[];if(state.intent){if(cat.includes(state.intent))s+=30;else if(state.intent==='eat'&&cat.some(x=>['breakfast','quick'].includes(x)))s+=18;else if(state.intent==='things'&&cat.includes('explore'))s+=15}if(best.includes(state.mode))s+=15;if(state.filters.budget&&place.budget.max<=state.filters.budget)s+=15;else if(state.filters.budget&&place.budget.min<=state.filters.budget)s+=6;if(state.filters.time&&place.duration.max<=state.filters.time)s+=10;else if(state.filters.time&&place.duration.min<=state.filters.time)s+=5;if(cls.includes('localFavorite')&&state.mode==='local')s+=8;if(cls.includes('hiddenGem')&&state.mode==='explorer')s+=8;if(cls.includes('worthTheTrip')&&state.mode==='visitor')s+=6;if(state.filters.nearby&&place.area)s+=2;return s}
function getPlaces(){return (window.WORTHGO_DATA?.[state.city]||[]).map(p=>({...p,_score:score(p)})).sort((a,b)=>b._score-a._score)}
function card(p){const cls=p.classification||[];const label=cls.includes('hiddenGem')?'✦ Hidden gem':cls.includes('worthTheTrip')?'📍 Worth the trip':'🏠 Local favorite';const budget=p.budget.currency==='INR'?'₹':'AED ';const img=p.type==='experience'?'explore-img':(p.subtypes||[]).includes('cafe')?'hidden-img':'breakfast-img';return `<article class="place-card"><div class="place-image ${img}"><span class="image-label">${label}</span><button class="save" type="button" aria-label="Save ${p.name}">♡</button></div><div class="place-body"><div class="place-meta"><span>${(p.subtypes||['Discovery'])[0]}</span><span>${budget}${p.budget.max}</span></div><h3>${p.name}</h3><p>${p.whyGo}</p><div class="place-footer"><span>📍 ${p.area}</span><span>${p.duration.min}–${p.duration.max} min</span></div><p class="recommendation-reason"><strong>WorthGo says:</strong> ${p.whySkip}</p></div></article>`}
function renderRecommendations(){const host=$('.cards');if(!host||!window.WORTHGO_DATA)return;let places=getPlaces();if(state.intent==='hidden')places=places.filter(p=>(p.classification||[]).includes('hiddenGem'));if(state.filters.budget)places=places.filter(p=>p.budget.min<=state.filters.budget);if(state.filters.time)places=places.filter(p=>p.duration.min<=state.filters.time);if(!places.length)places=getPlaces();host.innerHTML=places.slice(0,3).map(card).join('');host.querySelectorAll('.save').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();b.textContent=b.textContent==='♡'?'♥':'♡';toast(b.textContent==='♥'?'Saved locally':'Removed from saved places')}))}
function applyFilter(f){if(f==='budget'){state.filters.budget=budgetLimit();state.filters.time=null;toast(`${currency()==='INR'?'₹':'AED '}${budgetLimit()} budget filter applied.`)}if(f==='time'){state.filters.time=120;state.filters.budget=null;toast('2-hour filter applied.')}if(f==='nearby'){state.filters.nearby=true;toast('Nearby mode is ready — choose a city area next.')}renderRecommendations();$('.discover')?.scrollIntoView({behavior:'smooth',block:'start'})}
$$('.mode').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.mode)));
$$('[data-mode-jump]').forEach(b=>b.addEventListener('click',()=>{setMode(b.dataset.modeJump);$('.finder').scrollIntoView({behavior:'smooth',block:'center'})}));
$$('.intent').forEach(b=>b.addEventListener('click',()=>{state.intent=b.dataset.intent;$$('.intent').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state.filters.nearby=false;renderRecommendations();const name=b.querySelector('strong').textContent;toast(`${name} selected — WorthGo is ranking the best matches.`);$('.discover')?.scrollIntoView({behavior:'smooth',block:'start'})}));
$$('[data-filter]').forEach(b=>b.addEventListener('click',()=>applyFilter(b.dataset.filter)));
$$('.collection-row button').forEach(b=>b.addEventListener('click',()=>{const intent=b.dataset.intent;if(intent){const target=$(`.intent[data-intent="${intent}"]`);if(target)target.click()}else if(b.dataset.filter)applyFilter(b.dataset.filter)}));
$$('[data-action="finder"]').forEach(b=>b.addEventListener('click',()=>$('.finder').scrollIntoView({behavior:'smooth',block:'center'})));
$('.city-pill').addEventListener('click',()=>{state.city=state.city==='Hyderabad'?'Dubai':'Hyderabad';state.filters.budget=null;state.filters.time=null;state.filters.nearby=false;$('.city-pill').innerHTML=(state.city==='Hyderabad'?'🇮🇳 Hyderabad':'🇦🇪 Dubai')+' <span>⌄</span>';updateContext();renderRecommendations();toast(`${state.city} selected`)});
$('.menu-btn').addEventListener('click',()=>toast('WorthGo navigation is coming next — discovery engine is now connected.'));
updateContext();renderRecommendations();