const state={city:'Hyderabad',mode:'local',intent:null,filters:{budget:null,time:null,nearby:false,area:null,companions:null,mood:null,venue:null,food:null,meal:null,experience:null}};
const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);let toastTimer;let renderQueued=false;const normalizedCache=new WeakMap();
const CITY={Hyderabad:{currency:'INR',symbol:'₹',budget:[100,250,500,1000],areas:['Any area','Old City','Central Hyderabad','Jubilee Hills','Gachibowli','Secunderabad','Koti','Begum Bazar','Ghansi Bazaar']},Dubai:{currency:'AED',symbol:'AED ',budget:[20,50,100,250],areas:['Any area','Al Fahidi','Bur Bur Dubai','Deira','Dubai Marina','Downtown Dubai','Al Satwa','Karama','Jumeirah','JLT','Al Quoz']}};
const PHOTO={'Ram Ki Bandi':{file:'Ram Ki Bandi Dosa.jpg',credit:'Maharana7573 / Wikimedia Commons'},'Cafe Niloufer — Lakdikapul':{file:'Café Niloufer, Hyderabad.jpg',credit:'Mohammad Anees Qamar / Wikimedia Commons'},'Hotel Shadab':{file:'Shadab hotel.JPG',credit:'Randhir / Wikimedia Commons'},'Karachi Bakery':{file:'Karachi bakery.jpg',credit:'veera.sj / Wikimedia Commons'},'Charminar':{file:'CharMinar-Hyderabad.jpg',credit:'Wikimedia Commons'},'Golconda Fort':{file:'Golconda Fort, Hyderabad.jpg',credit:'Rini Basu 10 / Wikimedia Commons'},'Salar Jung Museum':{file:'Salar Jung Museum.jpg',credit:'Bernard Gagnon / Wikimedia Commons'},'Al Ustad Special Kabab':{file:'Al Ustad Special Kabab (45904790751).jpg',credit:'Ankur P / Wikimedia Commons'},'Bu Qtair':{file:'Bu Qtair Restaurant (32046167998).jpg',credit:'Ankur P / Wikimedia Commons'},'Al Fahidi Historical Neighbourhood':{file:'Al Fahidi Historical Neighbourhood, Dubai.jpg',credit:'Wikimedia Commons'},'Al Seef':{file:'Al Seef Dubai.jpg',credit:'Philosographer / Wikimedia Commons'}};
function photoUrl(name){const p=PHOTO[name];return p?`https://commons.wikimedia.org/wiki/Special:FilePath/${encodeURIComponent(p.file)}`:''}
function toast(msg){let el=$('#toast');if(!el){el=document.createElement('div');el.id='toast';el.className='toast';document.body.appendChild(el)}el.textContent=msg;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2400)}
function cityCfg(){return CITY[state.city]}
function modeLabel(){return state.mode==='local'?'locals':state.mode==='visitor'?'visitors':'explorers'}
function updateContext(){const el=$('#contextLabel');if(el){const extra=state.filters.area&&state.filters.area!=='Any area'?` · ${state.filters.area}`:'';el.textContent=`For ${modeLabel()} in ${state.city}${extra}`}}
function normalize(p){if(!p)return p;let n=normalizedCache.get(p);if(!n){n=window.WORTHGO_TAXONOMY?.normalize?window.WORTHGO_TAXONOMY.normalize(p):p;normalizedCache.set(p,n)}return n}
function setMode(mode){state.mode=mode;$$('.mode').forEach(b=>{const active=b.dataset.mode===mode;b.classList.toggle('active',active);b.setAttribute('aria-selected',String(active))});updateContext();queueRender()}
function score(place,n){let s=0;const cat=place.categories||[],best=place.bestFor||[],cls=place.classification||[],review=place.reviewSignal||place.reviewSignals,t=n||normalize(place);
if(state.intent){if(cat.includes(state.intent))s+=30;else if(state.intent==='eat'&&cat.some(x=>['breakfast','quick'].includes(x)))s+=18;else if(state.intent==='things'&&cat.includes('explore'))s+=15}
if(best.includes(state.mode))s+=15;
if(state.filters.budget){if(place.budget?.max<=state.filters.budget)s+=15;else if(place.budget?.min<=state.filters.budget)s+=6;else s-=10}
if(state.filters.time){if(place.duration?.max<=state.filters.time)s+=10;else if(place.duration?.min<=state.filters.time)s+=5;else s-=8}
if(state.filters.area&&state.filters.area!=='Any area'){if(place.area===state.filters.area)s+=18;else s-=4}
if(state.filters.companions&&best.includes(state.filters.companions))s+=10;if(state.filters.mood&&(place.moods||[]).includes(state.filters.mood))s+=8;
if(state.filters.venue&&t.venueType===state.filters.venue)s+=18;if(state.filters.food&&(t.foodCategories||[]).includes(state.filters.food))s+=20;if(state.filters.meal&&(t.mealTimes||[]).includes(state.filters.meal))s+=18;if(state.filters.experience&&(t.experienceTags||[]).includes(state.filters.experience))s+=16;
if(cls.includes('localFavorite')&&state.mode==='local')s+=8;if(cls.includes('hiddenGem')&&state.mode==='explorer')s+=8;if(cls.includes('worthTheTrip')&&state.mode==='visitor')s+=6;if(state.filters.nearby&&place.area)s+=2;
if(review){const rating=Number(review.rating??review.googleRating);const count=Number(review.reviewCount??review.googleReviewCount);if(rating>=4.4)s+=4;else if(rating>=4.1)s+=2;if(count>=1000)s+=2;else if(count>=100)s+=1}
const confidence=Number(place.researchConfidence)||0;return s+Math.min(8,confidence/12.5)}
function getPlaces(){return (window.WORTHGO_DATA?.[state.city]||[]).map(p=>{const n=normalize(p);return {...p,_normalized:n,_score:score(p,n)}}).sort((a,b)=>b._score-a._score)}
function fitReason(p){const reasons=[];const t=p._normalized||p;if(state.intent)reasons.push(state.intent==='hidden'?'a hidden-gem match':`${state.intent} match`);if(state.filters.venue&&t.venueType===state.filters.venue)reasons.push(t.venueType);if(state.filters.food&&(t.foodCategories||[]).includes(state.filters.food))reasons.push(state.filters.food);if(state.filters.meal&&(t.mealTimes||[]).includes(state.filters.meal))reasons.push(state.filters.meal);if(state.filters.experience&&(t.experienceTags||[]).includes(state.filters.experience))reasons.push(state.filters.experience);if(state.filters.budget&&p.budget?.max<=state.filters.budget)reasons.push('within budget');if(state.filters.time&&p.duration?.max<=state.filters.time)reasons.push('fits your time');if(state.filters.area&&state.filters.area!=='Any area'&&p.area===state.filters.area)reasons.push('in your area');if((p.bestFor||[]).includes(state.mode))reasons.push(`good for ${modeLabel()}`);return reasons.slice(0,3).join(' · ')||`strong match for ${modeLabel()}`}
function researchLine(p){const r=p.reviewSignal||p.reviewSignals;const confidence=Number(p.researchConfidence)||0;if(!r&&!confidence)return '';let signal='';if(r){const rating=r.rating??r.googleRating;const count=r.reviewCount??r.googleReviewCount;if(rating)signal=`${rating}/5`;if(count)signal+=` · ${count>=1000?`${Math.round(count/1000)}k+ reviews`:count>=100?`${count}+ reviews`:`${count} reviews`}`}const q=confidence>=85?'Verified':confidence>=70?'Strong research':confidence>=55?'Researching':'Needs verification';return `<span class="research-signal">${q} · ${confidence?Math.round(confidence):'—'}/100${signal?' · '+signal:''}</span>`}
function card(p,big=false){const cls=p.classification||[];const label=cls.includes('hiddenGem')?'✦ Hidden gem':cls.includes('worthTheTrip')?'📍 Worth the trip':'🏠 Local favorite';const symbol=cityCfg().symbol;const img=photoUrl(p.name);const photo=PHOTO[p.name];const fallback=p.type==='experience'?'explore-img':(p.subtypes||[]).includes('cafe')?'hidden-img':'breakfast-img';const t=p._normalized||p;return `<article class="place-card ${big?'card-big':''}"><div class="place-image ${fallback}">${img?`<img class="place-photo" src="${img}" alt="${p.name}" loading="lazy" decoding="async" onerror="this.style.display='none'"><span class="photo-credit">Photo: ${photo.credit}</span>`:'<span class="photo-missing">WorthGo photo coming soon</span>'}<span class="image-label">${label}</span><button class="save" type="button" aria-label="Save ${p.name}">♡</button></div><div class="place-body"><div class="place-meta"><span>${t.venueType||((p.subtypes||['Discovery'])[0])}</span><span>${symbol}${p.budget?.max??'—'}</span></div><h3>${p.name}</h3><p>${p.whyGo||'A WorthGo research pick.'}</p><div class="tag-row">${(t.foodCategories||[]).slice(0,2).map(x=>`<span>${x}</span>`).join('')}${t.mealTimes?.[0]?`<span>${t.mealTimes[0]}</span>`:''}</div><div class="fit-line">✓ ${fitReason(p)}</div>${researchLine(p)}<div class="place-footer"><span>📍 ${p.area||state.city}</span><span>${p.duration?.min??'—'}–${p.duration?.max??'—'} min</span></div><p class="recommendation-reason"><strong>Why skip?</strong> ${p.whySkip||'Check current details before travelling.'}</p><button class="add-day" type="button" data-add-day="${p.id}">＋ Add to My Day</button></div></article>`}
function buildDay(p){const places=getPlaces().filter(x=>x!==p).slice(0,2);openQuick('Your WorthGo mini-plan', [p,...places].map((x,i)=>`${i+1}. ${x.name} · ${x.duration?.min??'—'}–${x.duration?.max??'—'} min`),()=>toast('Mini-plan selected — add the places you want to My Day.'))}
function renderRecommendations(){renderQueued=false;const host=$('.cards');if(!host||!window.WORTHGO_DATA)return;let places=getPlaces();if(state.intent==='hidden')places=places.filter(p=>(p.classification||[]).includes('hiddenGem'));if(state.filters.budget)places=places.filter(p=>(p.budget?.min??Infinity)<=state.filters.budget);if(state.filters.time)places=places.filter(p=>(p.duration?.min??Infinity)<=state.filters.time);if(state.filters.area&&state.filters.area!=='Any area'){const exact=places.filter(p=>p.area===state.filters.area);if(exact.length)places=exact}
if(state.filters.venue)places=places.filter(p=>p._normalized?.venueType===state.filters.venue);if(state.filters.food)places=places.filter(p=>(p._normalized?.foodCategories||[]).includes(state.filters.food));if(state.filters.meal)places=places.filter(p=>(p._normalized?.mealTimes||[]).includes(state.filters.meal));if(state.filters.experience)places=places.filter(p=>(p._normalized?.experienceTags||[]).includes(state.filters.experience));if(!places.length)places=getPlaces();const best=places[0];const alternates=places.slice(1,3);const discover=$('.discover');if(!best)return;discover.querySelector('.section-intro h2').textContent='Your WorthGo picks';let badge=discover.querySelector('.result-summary');if(!badge){badge=document.createElement('div');badge.className='result-summary';discover.querySelector('.section-intro').appendChild(badge)}badge.innerHTML=`<strong>Best match</strong><span>${best.name}</span><small>${fitReason(best)}</small>`;host.innerHTML=card(best,true)+alternates.map(card).join('');host.querySelectorAll('.save').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();b.textContent=b.textContent==='♡'?'♥':'♡';toast(b.textContent==='♥'?'Saved locally':'Removed from saved places')}));host.querySelectorAll('[data-add-day]').forEach(b=>b.addEventListener('click',()=>{const p=places.find(x=>String(x.id)===String(b.dataset.addDay));if(window.WORTHGO_DAY?.add&&p)window.WORTHGO_DAY.add(p);else toast('My Day is ready — use the My Day button in the header.')}));let action=discover.querySelector('.result-actions');if(!action){action=document.createElement('div');action.className='result-actions';host.after(action)}action.innerHTML=`<button class="outline-btn" data-build="1">🗺️ Build a day from these</button><button class="light-btn" data-reset="1">↺ Reset choices</button>`;action.querySelector('[data-build]').onclick=()=>buildDay(best);action.querySelector('[data-reset]').onclick=resetFilters}
function queueRender(scroll=false){if(renderQueued)return;renderQueued=true;requestAnimationFrame(()=>{renderRecommendations();if(scroll)requestAnimationFrame(()=>$('.discover')?.scrollIntoView({behavior:'smooth',block:'start'}))})}
function resetFilters(){state.intent=null;state.filters={budget:null,time:null,nearby:false,area:null,companions:null,mood:null,venue:null,food:null,meal:null,experience:null};$$('.intent').forEach(x=>x.classList.remove('selected'));$$('.advanced-filter').forEach(x=>x.value='');updateContext();queueRender();toast('Finder choices reset')}
function applyFilter(f){if(f==='budget'){const limits=cityCfg().budget;state.filters.budget=limits[2];state.filters.time=null;toast(`${cityCfg().symbol}${limits[2]} budget filter applied.`)}if(f==='time'){state.filters.time=120;state.filters.budget=null;toast('2-hour mode applied.')}if(f==='nearby'){state.filters.nearby=true;toast('Nearby mode selected — choose your area below.')}updateContext();queueRender(true)}
function openQuick(title,options,apply){let panel=$('#quickPanel');if(!panel){panel=document.createElement('div');panel.id='quickPanel';panel.className='quick-panel';document.body.appendChild(panel)}panel.innerHTML=`<div class="quick-backdrop"></div><div class="quick-sheet"><button class="quick-close" aria-label="Close">×</button><span class="kicker">WORTHGO QUICK PICK</span><h2>${title}</h2><div class="quick-options">${options.map((o,i)=>`<button data-i="${i}">${o}</button>`).join('')}</div></div>`;panel.classList.add('show');panel.querySelector('.quick-close').onclick=()=>panel.classList.remove('show');panel.querySelector('.quick-backdrop').onclick=()=>panel.classList.remove('show');panel.querySelectorAll('.quick-options button').forEach(b=>b.onclick=()=>{apply(options[Number(b.dataset.i)]);panel.classList.remove('show');queueRender(true);updateContext()})}
function chooseArea(){openQuick('Where should we look?',cityCfg().areas,a=>{state.filters.area=a;state.filters.nearby=false;toast(a==='Any area'?`Searching all of ${state.city}`:`Searching ${a}`)})}
function hungry(){const opts=state.city==='Hyderabad'?['Breakfast & tiffin','Snacks & quick bites','Biryani & meals','Cafés & coffee']:['Karak & snacks','Indian & South Asian','Arabic food','Cafés & coffee'];openQuick('I’m hungry. What sounds good?',opts,a=>{const map=state.city==='Hyderabad'?{'Breakfast & tiffin':'breakfast','Snacks & quick bites':'quick','Biryani & meals':'eat','Cafés & coffee':'date'}:{'Karak & snacks':'quick','Indian & South Asian':'eat','Arabic food':'eat','Cafés & coffee':'date'};state.intent=map[a];$$('.intent').forEach(x=>x.classList.toggle('selected',x.dataset.intent===state.intent));toast(`${a} selected`)})}
function twoHours(){state.filters.time=120;state.intent='things';state.filters.budget=null;$$('.intent').forEach(x=>x.classList.toggle('selected',x.dataset.intent==='things'));toast('Finding ideas that fit inside two hours.');queueRender(true)}
function addAdvancedFilters(){const finder=$('.finder');if(!finder||$('.advanced-filters')||!window.WORTHGO_TAXONOMY)return;const box=document.createElement('div');box.className='advanced-filters';box.innerHTML=`<div class="advanced-heading"><strong>Refine your match</strong><span>Combine filters — WorthGo ranks the fit</span></div><div class="advanced-grid"><label>Venue<select class="advanced-filter" data-advanced="venue"><option value="">Any type</option>${window.WORTHGO_TAXONOMY.venueTypes.map(x=>`<option>${x}</option>`).join('')}</select></label><label>Food<select class="advanced-filter" data-advanced="food"><option value="">Any food</option>${window.WORTHGO_TAXONOMY.foodCategories.map(x=>`<option>${x}</option>`).join('')}</select></label><label>When<select class="advanced-filter" data-advanced="meal"><option value="">Any time</option>${window.WORTHGO_TAXONOMY.mealTimes.map(x=>`<option>${x}</option>`).join('')}</select></label><label>Experience<select class="advanced-filter" data-advanced="experience"><option value="">Any vibe</option>${window.WORTHGO_TAXONOMY.experiences.map(x=>`<option>${x}</option>`).join('')}</select></label></div>`;finder.appendChild(box);box.querySelectorAll('[data-advanced]').forEach(sel=>sel.addEventListener('change',()=>{state.filters[sel.dataset.advanced]=sel.value||null;updateContext();queueRender(true)}))}
$$('.mode').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.mode)));
$$('[data-mode-jump]').forEach(b=>b.addEventListener('click',()=>{setMode(b.dataset.modeJump);$('.finder').scrollIntoView({behavior:'smooth',block:'center'})}));
$$('.intent').forEach(b=>b.addEventListener('click',()=>{state.intent=b.dataset.intent;$$('.intent').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state.filters.nearby=false;queueRender(true);toast(`${b.querySelector('strong').textContent} selected — ranking your matches.`)}));
$$('[data-filter]').forEach(b=>b.addEventListener('click',()=>applyFilter(b.dataset.filter)));
$$('.collection-row button').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.intent){const target=$(`.intent[data-intent="${b.dataset.intent}"]`);if(target)target.click()}else if(b.dataset.filter)applyFilter(b.dataset.filter)}));
$$('[data-action="finder"]').forEach(b=>b.addEventListener('click',()=>$('.finder').scrollIntoView({behavior:'smooth',block:'center'})));
$('.city-pill').addEventListener('click',()=>{state.city=state.city==='Hyderabad'?'Dubai':'Hyderabad';state.filters={budget:null,time:null,nearby:false,area:null,companions:null,mood:null,venue:null,food:null,meal:null,experience:null};$('.city-pill').innerHTML=(state.city==='Hyderabad'?'🇮🇳 Hyderabad':'🇦🇪 Dubai')+' <span>⌄</span>';document.querySelectorAll('.advanced-filter').forEach(x=>x.value='');updateContext();queueRender();toast(`${state.city} selected`)});
$('.menu-btn').addEventListener('click',()=>toast('More WorthGo features will arrive after the core Finder is finished.'));
const quickRow=$('.quick-row');if(quickRow){const nearby=quickRow.querySelector('[data-filter="nearby"]');if(nearby)nearby.addEventListener('click',chooseArea);quickRow.insertAdjacentHTML('beforeend','<button type="button" data-quick="hungry">🍴 I’m hungry</button><button type="button" data-quick="two-hours">⏱ 2-hour plan</button>');quickRow.querySelector('[data-quick="hungry"]').addEventListener('click',hungry);quickRow.querySelector('[data-quick="two-hours"]').addEventListener('click',twoHours)}
updateContext();addAdvancedFilters();renderRecommendations();
