window.WORTHGO_DATA={
  Hyderabad:[
    {id:'hyd-tiffin-01',name:'Old-school tiffin spot',type:'food',subtypes:['tiffin','breakfast'],categories:['eat','breakfast','quick'],cuisines:['South Indian'],tags:['local-favorite','budget','quick'],budget:{min:60,max:250,currency:'INR'},duration:{min:20,max:60},bestFor:['local','visitor','explorer'],moods:['comfort','classic'],classification:['localFavorite'],area:'Central Hyderabad',whyGo:'A practical starting point for a classic Hyderabad morning when you want filling tiffin without spending much.',whySkip:'Skip if you want a quiet premium café experience.',highlights:['Fast breakfast','Budget friendly','Traditional tiffin'],lastVerified:'2026-08-15',verificationStatus:'seed'},
    {id:'hyd-hidden-01',name:'A quiet café corner',type:'food',subtypes:['cafe','coffee'],categories:['eat','hidden','date'],cuisines:['Cafe'],tags:['hidden-gem','quiet','conversation'],budget:{min:180,max:500,currency:'INR'},duration:{min:45,max:120},bestFor:['local','explorer'],moods:['quiet','slow'],classification:['hiddenGem'],area:'Jubilee Hills',whyGo:'A slower option for coffee, conversation and discovering something outside the usual list.',whySkip:'Skip if you only have a few minutes or want street food.',highlights:['Quiet vibe','Good for conversation','Longer visit'],lastVerified:'2026-08-15',verificationStatus:'seed'},
    {id:'hyd-oldcity-01',name:'Old City discovery loop',type:'experience',subtypes:['walk','culture','food'],categories:['explore','things','hidden'],tags:['worth-trip','culture','walkable'],budget:{min:0,max:500,currency:'INR'},duration:{min:120,max:240},bestFor:['visitor','explorer','local'],moods:['curious','historic'],classification:['worthTheTrip'],area:'Old City',whyGo:'A compact way to combine heritage, markets and local food in one outing.',whySkip:'Skip in extreme heat if you are not comfortable walking outdoors.',highlights:['Heritage','Markets','Local food'],lastVerified:'2026-08-15',verificationStatus:'seed'}
  ],
  Dubai:[
    {id:'dub-karak-01',name:'Local-style karak & quick bite',type:'food',subtypes:['karak','snack','cafeteria'],categories:['eat','quick','breakfast'],cuisines:['Gulf','Indian'],tags:['local-favorite','budget','quick'],budget:{min:5,max:30,currency:'AED'},duration:{min:15,max:45},bestFor:['local','visitor','explorer'],moods:['casual','quick'],classification:['localFavorite'],area:'Bur Dubai',whyGo:'A low-cost way to experience everyday Dubai food culture rather than only destination dining.',whySkip:'Skip if you are looking for a formal sit-down meal.',highlights:['Quick stop','Budget friendly','Everyday local feel'],lastVerified:'2026-08-15',verificationStatus:'seed'},
    {id:'dub-fahidi-01',name:'Al Fahidi old-neighbourhood walk',type:'experience',subtypes:['culture','walk','heritage'],categories:['explore','things','hidden'],tags:['culture','historic','walkable'],budget:{min:0,max:100,currency:'AED'},duration:{min:90,max:180},bestFor:['visitor','explorer','local'],moods:['curious','historic'],classification:['worthTheTrip'],area:'Al Fahidi',whyGo:'A strong first introduction to old Dubai, with heritage streets and nearby cultural stops.',whySkip:'Skip if you want malls, beaches or a nightlife-focused plan.',highlights:['Old Dubai','Culture','Walkable'],lastVerified:'2026-08-15',verificationStatus:'seed'},
    {id:'dub-hidden-01',name:'A tucked-away coffee stop',type:'food',subtypes:['cafe','coffee'],categories:['eat','hidden','date'],cuisines:['Cafe'],tags:['hidden-gem','quiet','conversation'],budget:{min:20,max:80,currency:'AED'},duration:{min:45,max:120},bestFor:['local','explorer'],moods:['quiet','slow'],classification:['hiddenGem'],area:'Bur Dubai',whyGo:'A slower discovery option for people who want coffee and conversation away from the obvious tourist circuit.',whySkip:'Skip if your priority is a major landmark or a very short stop.',highlights:['Quiet break','Coffee','Easy add-on'],lastVerified:'2026-08-15',verificationStatus:'seed'}
  ]
};