(() => {
  const SAVE_KEY='worthgo-saved-v1';
  const getSaved=()=>{try{return JSON.parse(localStorage.getItem(SAVE_KEY)||'[]')}catch{return[]}};
  const setSaved=items=>localStorage.setItem(SAVE_KEY,JSON.stringify([...new Set(items)].slice(0,100)));
  const toast=msg=>window.toast?.(msg)||(()=>{const t=document.createElement('div');t.className='toast show';t.textContent=msg;document.body.appendChild(t);setTimeout(()=>t.remove(),1800)})();
  const placeName=card=>card?.querySelector('h3')?.textContent.trim();
  const persistCardSave=card=>{const name=placeName(card);if(!name)return;const saved=getSaved();const button=card.querySelector('.save');if(!button)return;const isSaved=saved.includes(name);const nextSaved=!isSaved;setSaved(nextSaved?[...saved,name]:saved.filter(x=>x!==name));const text=nextSaved?'♥':'♡';if(button.textContent!==text)button.textContent=text;if(button.getAttribute('aria-pressed')!==String(nextSaved))button.setAttribute('aria-pressed',String(nextSaved));toast(nextSaved?'Saved locally':'Removed from saved places')};
  const syncSaveButtons=()=>document.querySelectorAll('.place-card .save').forEach(b=>{const card=b.closest('.place-card');const saved=getSaved().includes(placeName(card));const text=saved?'♥':'♡';const pressed=String(saved);if(b.textContent!==text)b.textContent=text;if(b.getAttribute('aria-pressed')!==pressed)b.setAttribute('aria-pressed',pressed)});
  const fixBuildDay=()=>{const button=document.querySelector('[data-build]');if(!button||button.dataset.wgFixed)return;button.dataset.wgFixed='1';button.addEventListener('click',()=>{setTimeout(()=>{const names=[...document.querySelectorAll('.place-card h3')].slice(0,3).map(x=>x.textContent.trim()).filter(Boolean);if(window.WORTHGO_DAY?.add&&names.length){names.forEach(name=>window.WORTHGO_DAY.add(name));toast(`${names.length} places added to My Day`)}},50)});};
  const shareDetail=async e=>{const btn=e.target.closest('[data-share-detail]');if(!btn)return;const modal=btn.closest('.wg-modal');const name=modal?.querySelector('h2')?.textContent.trim();if(!name)return;const city=/Dubai/i.test(document.querySelector('.city-pill')?.textContent||'')?'Dubai':'Hyderabad';const place=Object.values(window.WORTHGO_DATA||{}).flat().find(p=>p.name===name);const id=place?.id||name;const url=`${location.origin}${location.pathname}?city=${encodeURIComponent(city)}&place=${encodeURIComponent(id)}`;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();try{if(navigator.share)await navigator.share({title:`${name} · WorthGo`,text:`${name} — WorthGo`,url});else{await navigator.clipboard.writeText(url);toast('Place link copied')}}catch{toast('Place link ready to share')}};
  const runQuery=()=>{const q=new URLSearchParams(location.search).get('q');if(!q)return;const input=document.querySelector('#wgSearch');if(!input)return;input.value=q;document.querySelector('#wgSearchBtn')?.click()};
  const fixCityPlaceUrl=()=>{const params=new URLSearchParams(location.search);const requestedCity=params.get('city');const place=params.get('place');if(!requestedCity||!place||!/^(Hyderabad|Dubai)$/i.test(requestedCity))return;const current=/Dubai/i.test(document.querySelector('.city-pill')?.textContent||'')?'Dubai':'Hyderabad';if(current.toLowerCase()===requestedCity.toLowerCase()){setTimeout(()=>window.dispatchEvent(new PopStateEvent('popstate')),0);return}const pill=document.querySelector('.city-pill');if(!pill)return;pill.click();setTimeout(()=>{const option=[...document.querySelectorAll('.quick-options button,.quick-sheet button')].find(b=>b.textContent.trim().toLowerCase().includes(requestedCity.toLowerCase()));if(option){option.click();setTimeout(()=>window.dispatchEvent(new PopStateEvent('popstate')),220)}},100)};
  const installFilterGoUX=()=>{const box=document.querySelector('.advanced-filters');if(!box||box.dataset.wgGoInstalled)return;box.dataset.wgGoInstalled='1';const grid=box.querySelector('.advanced-grid');if(!grid)return;const actions=document.createElement('div');actions.className='wg-filter-actions';actions.innerHTML='<span class="wg-filter-hint" aria-live="polite">Choose any filters you want, compare the matches, then tap Go.</span><button type="button" class="primary-btn wg-filter-clear">Clear filters</button><button type="button" class="primary-btn wg-filter-go">Go to matches →</button>';grid.after(actions);const clear=actions.querySelector('.wg-filter-clear');clear.addEventListener('click',()=>{const reset=document.querySelector('.result-actions [data-reset]');if(reset){reset.click();}else{document.querySelectorAll('.advanced-filter').forEach(x=>x.value='');document.querySelectorAll('.intent.selected').forEach(x=>x.classList.remove('selected'));toast('Finder choices cleared');}});const go=actions.querySelector('.wg-filter-go');go.addEventListener('click',()=>{const discover=document.querySelector('.discover');if(!discover)return;discover.scrollIntoView({behavior:'smooth',block:'start'});setTimeout(()=>{const first=discover.querySelector('.place-card');first?.setAttribute('tabindex','-1');first?.focus({preventScroll:true});},450)});};
  const protectFilterScroll=()=>{document.addEventListener('change',e=>{const select=e.target.closest?.('.advanced-filter');if(!select)return;const box=select.closest('.advanced-filters');if(!box)return;const anchor=box.getBoundingClientRect().top+window.scrollY-16;const restore=()=>{if(document.activeElement===select||document.activeElement?.closest?.('.advanced-filters'))window.scrollTo({top:anchor,behavior:'auto'});};requestAnimationFrame(()=>requestAnimationFrame(restore));setTimeout(restore,140);setTimeout(restore,320)},true)};
  const updateFilterHint=()=>{const hint=document.querySelector('.wg-filter-hint');if(!hint)return;const selected=[...document.querySelectorAll('.advanced-filter')].filter(x=>x.value).length;hint.textContent=selected?`${selected} filter${selected===1?'':'s'} selected · compare the matches below, then tap Go.`:'Choose any filters you want, compare the matches, then tap Go.'};
  const removeDuplicateTimeQuickAction=()=>{document.querySelectorAll('.quick-row [data-quick="two-hours"]').forEach(el=>el.remove());};

  const fixStaleMenu=()=>{const replace=()=>document.querySelectorAll('body *').forEach(el=>{if(el.children.length===0&&/More WorthGo features will arrive after the core Finder is finished/i.test(el.textContent||''))el.textContent='Everything you need to discover, save and plan with WorthGo.'});replace();document.addEventListener('click',e=>{if(e.target.closest('.menu-btn'))setTimeout(replace,0)});};

  /* Browse-first experience: show the complete inventory for the active city until
     the visitor deliberately chooses a filter/intent. Filtering then narrows this
     same list. No DOM observer is used for this feature, avoiding freeze loops. */
  let browseAll=true;
  const browseStyles=()=>{if(document.getElementById('wg-browse-styles'))return;const s=document.createElement('style');s.id='wg-browse-styles';s.textContent='.wg-browse-summary{display:flex;gap:10px;align-items:center;flex-wrap:wrap;margin:0 0 16px}.wg-browse-summary strong{font-weight:700}.wg-browse-summary span{color:#777}.wg-browse-all .cards{grid-template-columns:repeat(2,minmax(0,1fr))}@media(max-width:720px){.wg-browse-all .cards{grid-template-columns:1fr}}';document.head.appendChild(s)};
  const showAllInventory=()=>{if(!browseAll||typeof getPlaces!=='function'||typeof card!=='function')return;const host=document.querySelector('.discover .cards');const discover=document.querySelector('.discover');if(!host||!discover)return;const places=getPlaces();if(!places.length)return;discover.classList.add('wg-browse-all');const title=discover.querySelector('.section-intro h2');if(title)title.textContent=`All places in ${typeof state!=='undefined'?state.city:'Hyderabad'}`;let badge=discover.querySelector('.wg-browse-summary');if(!badge){badge=document.createElement('div');badge.className='wg-browse-summary';discover.querySelector('.section-intro').appendChild(badge)}badge.innerHTML=`<strong>${places.length} places</strong><span>Browse everything first · use the filters above to narrow it down.</span>`;host.innerHTML=places.map((p,i)=>card(p,i===0)).join('');host.querySelectorAll('[data-add-day]').forEach(b=>b.addEventListener('click',()=>{const p=places.find(x=>String(x.id)===String(b.dataset.addDay));if(window.WORTHGO_DAY?.add&&p)window.WORTHGO_DAY.add(p)}));syncSaveButtons();fixBuildDay()};
  const switchToFiltered=()=>{browseAll=false;document.querySelector('.discover')?.classList.remove('wg-browse-all')};
  const switchToBrowse=()=>{browseAll=true;requestAnimationFrame(showAllInventory)};
  const installBrowseMode=()=>{document.addEventListener('click',e=>{const t=e.target.closest?.('.intent,[data-filter],[data-quick],[data-mode-jump],.city-pill,.collection-row button');if(!t)return;if(t.matches('.city-pill')||t.matches('[data-mode-jump]')||t.matches('.collection-row button[data-filter]')===false&&t.matches('.city-pill'))switchToBrowse();else switchToFiltered()},true);document.addEventListener('change',e=>{if(e.target.closest?.('.advanced-filter'))switchToFiltered()},true);document.addEventListener('click',e=>{if(e.target.closest?.('.wg-filter-clear,[data-reset]'))switchToBrowse()},true);browseStyles();showAllInventory()};

  const init=()=>{
    document.addEventListener('click',e=>{const save=e.target.closest('.place-card .save');if(save){e.preventDefault();e.stopPropagation();persistCardSave(save.closest('.place-card'))}},true);
    document.addEventListener('click',shareDetail,true);
    protectFilterScroll();
    let queued=false;
    const observer=new MutationObserver(()=>{if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;syncSaveButtons();fixBuildDay();installFilterGoUX();updateFilterHint();removeDuplicateTimeQuickAction()})});
    observer.observe(document.body,{childList:true,subtree:true});
    syncSaveButtons();
    fixBuildDay();
    installFilterGoUX();
    updateFilterHint();
    removeDuplicateTimeQuickAction();
    document.addEventListener('change',e=>{if(e.target.closest?.('.advanced-filter'))setTimeout(updateFilterHint,0)},true);
    runQuery();
    fixCityPlaceUrl();
    fixStaleMenu();
    installBrowseMode();
  };
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();