(() => {
  const SAVE_KEY='worthgo-saved-v1';
  const getSaved=()=>{try{return JSON.parse(localStorage.getItem(SAVE_KEY)||'[]')}catch{return[]}};
  const setSaved=items=>localStorage.setItem(SAVE_KEY,JSON.stringify([...new Set(items)].slice(0,100)));
  const toast=msg=>window.toast?.(msg)||(()=>{const t=document.createElement('div');t.className='toast show';t.textContent=msg;document.body.appendChild(t);setTimeout(()=>t.remove(),1800)})();
  const placeName=card=>card?.querySelector('h3')?.textContent.trim();
  const persistCardSave=(card)=>{const name=placeName(card);if(!name)return;const saved=getSaved();const button=card.querySelector('.save');if(!button)return;const isSaved=saved.includes(name);if(isSaved){setSaved(saved.filter(x=>x!==name));button.textContent='♡';button.setAttribute('aria-pressed','false')}else{setSaved([...saved,name]);button.textContent='♥';button.setAttribute('aria-pressed','true')}toast(isSaved?'Removed from saved places':'Saved locally')};
  const syncSaveButtons=()=>document.querySelectorAll('.place-card .save').forEach(b=>{const card=b.closest('.place-card');const saved=getSaved().includes(placeName(card));b.textContent=saved?'♥':'♡';b.setAttribute('aria-pressed',String(saved))});
  const fixBuildDay=()=>{const button=document.querySelector('[data-build]');if(!button||button.dataset.wgFixed)return;button.dataset.wgFixed='1';button.addEventListener('click',()=>{setTimeout(()=>{const names=[...document.querySelectorAll('.place-card h3')].slice(0,3).map(x=>x.textContent.trim()).filter(Boolean);if(window.WORTHGO_DAY?.add&&names.length){names.forEach(name=>window.WORTHGO_DAY.add(name));toast(`${names.length} places added to My Day`)}},50)},{capture:false})};
  const runQuery=()=>{const q=new URLSearchParams(location.search).get('q');if(!q)return;const input=document.querySelector('#wgSearch');if(!input)return;input.value=decodeURIComponent(q);document.querySelector('#wgSearchBtn')?.click()};
  const fixCityPlaceUrl=()=>{const params=new URLSearchParams(location.search);const requestedCity=params.get('city');const place=params.get('place');if(!requestedCity||!place)return;const current=/Dubai/i.test(document.querySelector('.city-pill')?.textContent||'')?'Dubai':'Hyderabad';if(current.toLowerCase()===requestedCity.toLowerCase())return;const pill=document.querySelector('.city-pill');if(!pill)return;pill.click();setTimeout(()=>{const option=[...document.querySelectorAll('.quick-options button,.quick-sheet button')].find(b=>b.textContent.trim().toLowerCase().includes(requestedCity.toLowerCase()));if(option){option.click();setTimeout(()=>{const input=document.querySelector('#wgSearch');if(input){input.value=decodeURIComponent(place);document.querySelector('#wgSearchBtn')?.click();setTimeout(()=>document.querySelector('#wgModal .wg-result')?.click(),80)}},120)}},80)};
  const fixStaleMenu=()=>{const replace=()=>document.querySelectorAll('body *').forEach(el=>{if(el.children.length===0&&/More WorthGo features will arrive after the core Finder is finished/i.test(el.textContent||'')){el.textContent='Everything you need to discover, save and plan with WorthGo.'}});replace();document.addEventListener('click',e=>{if(e.target.closest('.menu-btn'))setTimeout(replace,0)});};
  const init=()=>{document.addEventListener('click',e=>{const save=e.target.closest('.place-card .save');if(save){e.preventDefault();e.stopPropagation();persistCardSave(save.closest('.place-card'))}});const observer=new MutationObserver(()=>{syncSaveButtons();fixBuildDay()});observer.observe(document.body,{childList:true,subtree:true});syncSaveButtons();fixBuildDay();runQuery();fixCityPlaceUrl();fixStaleMenu()};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();