(() => {
  const SAVE_KEY='worthgo-saved-v1';
  const getSaved=()=>{try{return JSON.parse(localStorage.getItem(SAVE_KEY)||'[]')}catch{return[]}};
  const setSaved=x=>localStorage.setItem(SAVE_KEY,JSON.stringify([...new Set(x)].slice(0,100)));
  const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  const city=()=>{const t=document.querySelector('.city-pill')?.textContent||'';return /Dubai/i.test(t)?'Dubai':'Hyderabad'};
  const places=()=>window.WORTHGO_DATA?.[city()]||[];
  const find=id=>places().find(p=>String(p.id)===String(id))||places().find(p=>p.name===id);
  const toast=msg=>window.toast?.(msg)||(()=>{const t=document.createElement('div');t.className='toast show';t.textContent=msg;document.body.appendChild(t);setTimeout(()=>t.remove(),1800)})();
  const ensureShell=()=>{
    if(!document.querySelector('.wg-search-launch')){
      const finder=document.querySelector('.finder .intent-grid');
      if(finder){const box=document.createElement('div');box.className='wg-search-launch';box.innerHTML='<label><span>SEARCH WORTHGO</span><input id="wgSearch" type="search" placeholder="Search a place, food, area or experience…" autocomplete="off"><button type="button" id="wgSearchBtn">Search</button></label>';finder.before(box)}
    }
    if(!document.querySelector('#wgModal')){const m=document.createElement('div');m.id='wgModal';m.className='wg-modal';m.setAttribute('aria-hidden','true');document.body.appendChild(m)}
    if(!document.querySelector('#wgSaved')){const s=document.createElement('div');s.id='wgSaved';s.className='wg-modal';s.setAttribute('aria-hidden','true');document.body.appendChild(s)}
    if(!document.querySelector('.wg-saved-btn')){const h=document.querySelector('.header-actions');const day=h?.querySelector('.day-pill');if(h&&day){const b=document.createElement('button');b.className='wg-saved-btn';b.type='button';b.textContent='♡ Saved';b.onclick=showSaved;h.insertBefore(b,day)}}
  };
  const openModal=(p)=>{if(!p)return;const saved=getSaved().includes(p.name);const r=p.reviewSignal||p.reviewSignals||{};const modal=document.querySelector('#wgModal');modal.innerHTML=`<div class="wg-backdrop"></div><article class="wg-detail"><button class="wg-close" aria-label="Close">×</button><span class="kicker">WORTHGO DETAIL</span><h2>${esc(p.name)}</h2><p class="wg-detail-meta">📍 ${esc(p.area||city())} · ${esc(p.venueType||p.type||'Discovery')} · ${esc(p.duration?.min??'—')}–${esc(p.duration?.max??'—')} min</p><div class="wg-detail-grid"><div><strong>Why go</strong><p>${esc(p.whyGo||'A WorthGo research pick.')}</p></div><div><strong>Why skip</strong><p>${esc(p.whySkip||'Check current details before travelling.')}</p></div><div><strong>Best for</strong><p>${esc((p.bestFor||[]).join(' · ')||'Locals and curious visitors')}</p></div><div><strong>Research</strong><p>${esc(p.researchConfidence?`${Math.round(p.researchConfidence)}/100 confidence`:'Research confidence unavailable')}${r.rating?` · ${esc(r.rating)}/5`:''}</p></div></div><div class="wg-detail-actions"><a class="primary-btn" target="_blank" rel="noopener noreferrer" href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${p.name}, ${p.area||''}, ${city()}`)}">📍 Directions</a><button class="outline-btn" data-save-detail>${saved?'♥ Saved':'♡ Save place'}</button><button class="light-btn" data-day-detail>＋ My Day</button></div></article>`;modal.classList.add('show');modal.setAttribute('aria-hidden','false');modal.querySelector('.wg-close').onclick=closeModal;modal.querySelector('.wg-backdrop').onclick=closeModal;modal.querySelector('[data-save-detail]').onclick=()=>{const a=getSaved();const i=a.indexOf(p.name);if(i>=0){a.splice(i,1);toast('Removed from saved places')}else{a.push(p.name);toast('Saved locally')}setSaved(a);modal.querySelector('[data-save-detail]').textContent=getSaved().includes(p.name)?'♥ Saved':'♡ Save place';updateSavedButton()};modal.querySelector('[data-day-detail]').onclick=()=>{if(window.WORTHGO_DAY?.add){window.WORTHGO_DAY.add(p);toast('Added to My Day')}else toast('My Day is unavailable')};};
  const closeModal=()=>{document.querySelectorAll('.wg-modal.show').forEach(x=>{x.classList.remove('show');x.setAttribute('aria-hidden','true')})};
  const resultHtml=p=>`<button class="wg-result" data-result="${esc(p.id??p.name)}"><strong>${esc(p.name)}</strong><span>${esc(p.area||city())} · ${esc(p.venueType||p.type||'Discovery')}</span><small>${esc(p.whyGo||'WorthGo pick')}</small></button>`;
  const search=(q)=>{const term=q.trim().toLowerCase();if(!term)return;const ranked=places().map(p=>{const hay=[p.name,p.area,p.whyGo,p.whySkip,p.type,...(p.categories||[]),...(p.subtypes||[])].join(' ').toLowerCase();let score=hay.includes(term)?10:0;if(String(p.name).toLowerCase().startsWith(term))score+=10;if(String(p.area||'').toLowerCase().includes(term))score+=5;return [p,score]}).filter(x=>x[1]>0).sort((a,b)=>b[1]-a[1]).slice(0,10).map(x=>x[0]);const m=document.querySelector('#wgModal');m.innerHTML=`<div class="wg-backdrop"></div><article class="wg-detail wg-search-results"><button class="wg-close" aria-label="Close">×</button><span class="kicker">SEARCH RESULTS</span><h2>${ranked.length?`Results for “${esc(q)}”`:'Nothing matched'}</h2><div class="wg-results">${ranked.map(resultHtml).join('')||'<p class="wg-empty">Try a place, area, food, or experience.</p>'}</div></article>`;m.classList.add('show');m.setAttribute('aria-hidden','false');m.querySelector('.wg-close').onclick=closeModal;m.querySelector('.wg-backdrop').onclick=closeModal;m.querySelectorAll('[data-result]').forEach(b=>b.onclick=()=>openModal(find(b.dataset.result)))};
  const showSaved=()=>{const names=getSaved();const ps=names.map(find).filter(Boolean);const m=document.querySelector('#wgSaved');m.innerHTML=`<div class="wg-backdrop"></div><article class="wg-detail wg-search-results"><button class="wg-close" aria-label="Close">×</button><span class="kicker">YOUR SAVED PLACES</span><h2>${ps.length?'Places you want to remember':'Nothing saved yet'}</h2>${ps.length?`<div class="wg-results">${ps.map(resultHtml).join('')}</div><button class="light-btn" data-clear-saved>Clear saved places</button>`:'<p class="wg-empty">Save a place from its details and it will stay on this device.</p>'}</article>`;m.classList.add('show');m.setAttribute('aria-hidden','false');m.querySelector('.wg-close').onclick=closeModal;m.querySelector('.wg-backdrop').onclick=closeModal;m.querySelectorAll('[data-result]').forEach(b=>b.onclick=()=>openModal(find(b.dataset.result)));m.querySelector('[data-clear-saved]')?.addEventListener('click',()=>{setSaved([]);updateSavedButton();showSaved();toast('Saved places cleared')})};
  const updateSavedButton=()=>{const b=document.querySelector('.wg-saved-btn');if(b)b.textContent=`♡ Saved${getSaved().length?` (${getSaved().length})`:''}`};
  const init=()=>{ensureShell();updateSavedButton();document.addEventListener('click',e=>{const card=e.target.closest('.place-card');if(card&&!e.target.closest('button,a')){const p=find(card.querySelector('h3')?.textContent.trim());if(p)openModal(p)}});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal();if(e.key==='/'&&!['INPUT','TEXTAREA'].includes(document.activeElement?.tagName)){e.preventDefault();document.querySelector('#wgSearch')?.focus()}});document.querySelector('#wgSearchBtn')?.addEventListener('click',()=>search(document.querySelector('#wgSearch')?.value||''));document.querySelector('#wgSearch')?.addEventListener('keydown',e=>{if(e.key==='Enter')search(e.target.value)})};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();